version: "3.9"

services:

  minio:
    image: minio/minio
    container_name: enterprise-minio

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

  postgres:
    image: postgres:16
    container_name: retail-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: retail
      POSTGRES_PASSWORD: retail123
      POSTGRES_DB: retail_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:

  minio_data:

  postgres_data: