spark:

  app_name: Enterprise Retail Lakehouse

  master: local[*]

  packages:
    - org.postgresql:postgresql:42.7.3
    - org.apache.hadoop:hadoop-aws:3.4.1

  configs:

    spark.sql.shuffle.partitions: "8"

    spark.sql.session.timeZone: UTC

    spark.driver.memory: "2g"

    spark.executor.memory: "2g"